name: Get Listings
run-name: ${{ github.actor }} gets listings

on:
  schedule:
    - cron: '0 14 * * *'  # Runs every day at 2 PM UTC (12 am AEST)
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  get_listings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true  # Enable Git LFS support

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run get_sold_listings
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MOTHERDUCK_TOKEN:  ${{ secrets.CLIENT_SECRET }}
        run: |
          python -m scripts.get_sold_listings
        continue-on-error: true

      - name: Run get_sale_listings
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          MOTHERDUCK_TOKEN:  ${{ secrets.CLIENT_SECRET }}
        run: |
          python -m scripts.get_sale_listings
        continue-on-error: true
