name: Get Listings
run-name: ${{ github.actor }} gets listings

on: [push]

jobs:
  get_listings:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run get_sold_listings
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python -m scripts.get_sold_listings || echo "get_sold_listings failed with error: $?"
        continue-on-error: true

      - name: Run get_sale_listings
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          python -m scripts.get_sale_listings || echo "get_sale_listings failed with error: $?"
        continue-on-error: true

      - name: Commit and push changes
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Automated update from GitHub Actions" || echo "No changes to commit"
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}